### ISSUE TITLE
Confusing redirects in the "progress" sample app

### ISSUE THREAD

**Issue by looppi** [livechat/sample-apps#1]
I tried to start developing LiveChat agent app yesterday and used "progress" sample as a basis for development. I got it running and encountered some very odd extra redirects at the authorization phase which seemingly didn't come from the app. The redirect had wrong app_client_id and such  it seemed I had no control over it.

After a few looks in the code, I found the culprit:
https://github.com/livechat/sample-apps/blob/master/progress/public/index.html#L36

I think this is unnecessary as the React app has similar logic inside it (https://github.com/livechat/sample-apps/blob/master/progress/src/App/Authorization.js#L19) and that code uses settings from Config.js (https://github.com/livechat/sample-apps/blob/master/progress/src/App/Config.js). I suggest removing the redirect code from index.html, so the next person trying these out, would get working sample app quicker.

**Comment by venits** [comment]
Yep, you are right :)
This problem only occurs in 'progress' because I forget to update index.html to newer version.
Sorry for for that. Now everything should work ;)
