### ISSUE TITLE
redirect uri is not one of client's allowed redirects

### ISSUE THREAD

**Issue by AmanMinhas** [livechat/sample-apps#2]
https://gyazo.com/650d307932965e7508d637e7824f0820

Getting this error in spite of whitelisting localhost:3000/ 
Could not successfully setup tag master project.

**Comment by venits** [comment]
Hi, It seems like you forgot to add `http://localhost:3000` to you app whitelist.
Please take a look at below picture:

<img width="600" alt="screen shot 2018-06-27 at 16 02 24" src="https://user-images.githubusercontent.com/31382349/41979081-807f30b6-7a23-11e8-97b4-4f12ca2d4fea.png">

You must do the same for you app.

Also make sure to follow all steps from README.md
