### ISSUE TITLE
LC3 Agent Bot : can't create bot

### ISSUE THREAD

**Issue by breadpanz** [livechat/sample-apps#3]
it seems like I don't have authorization even though I've checked all the scopes in Access scopes

![image](https://user-images.githubusercontent.com/45379896/53806629-668b0600-3f88-11e9-88b3-a5e6d12455c0.png)

**Comment by venits** [comment]
Hi, domain `localhost:61325` is not whitelisted on our side.
Please try using this site:
https://lacy-pixie.glitch.me/

If you want to develop it locally you will have to create new application in Developers Console and generate new `client_id` and `secret_id` and put it in your source code.

**Comment by breadpanz** [comment]
oh, yea, I tried to use https://lacy-pixie.glitch.me/ and it returns like this.

![image](https://user-images.githubusercontent.com/45379896/53811123-97246d00-3f93-11e9-9fef-d22a895f3a71.png)

and yes, I want to work on it in my local, what I did is create a new app. in Developers Console to generate `client_id `and `secret_id ` and whitelist my local as I saw it in here: 

https://developers.livechatinc.com/docs//authorization/#public-web-apps

**Comment by breadpanz** [comment]
here's my newly created app. in the Developers Console.

![image](https://user-images.githubusercontent.com/45379896/53811518-89231c00-3f94-11e9-8ade-5505e0c84401.png)

below App scopes is all checked.

**Comment by breadpanz** [comment]
Ohh. I see, okay I didn't notice the version, I thought that was automatic since I just registered yesterday. anyways, am gonna try to upgrade it and will let you know here if I have a luck to make it work in my local.

**Comment by breadpanz** [comment]
Hello, I am now using the LC3 protocol and it works like charm ;)

Thank you very much @venits

**Comment by breadpanz** [comment]
Hello, I am now using the LC3 protocol and it works like a charm ;)

Thank you very much @venits
