### ISSUE TITLE
can't acquire refresh_token

### ISSUE THREAD

**Issue by breadpanz** [livechat/sample-apps#5]
reference: https://developers.livechatinc.com/beta-docs/authorization/#step-4-exchange-code-for-access-token-and-refresh-token

I'm having a problem getting `refresh_token` when I try to request in https://accounts.livechatinc.com/token

It returns:

{"exception_description":"The authorization grant type is not supported by the authorization server.","oauth_exception":"unsupported_grant_type"}

Is there any way to use API key instead of OAuth here: https://developers.livechatinc.com/beta-docs/configuration-api/

**Comment by venits** [comment]
Hi,
it will work only for **side-server-apps** .
You have to change your application type in our developers console:

Please check picture below to change where you can find option to change your application type :)

<img width="985" alt="Screenshot 2019-03-27 at 11 51 00" src="https://user-images.githubusercontent.com/31382349/55070505-b2f8cb80-5086-11e9-99eb-36df32150359.png">

**Comment by breadpanz** [comment]
Hello again @venits, It shows that I am using the server side app.

![image](https://user-images.githubusercontent.com/45379896/55072253-94fe8b80-50c5-11e9-9ac9-83009a0c0bdc.png)

**Comment by venits** [comment]
Hmm are able to get `response_type=code` when doing your first redirect to our server?

The URI should look more less like that:
`https://accounts.livechatinc.com/
  ?response_type=code
  &client_id=86pp8cqeg2ac5fimbs8gibluu16ugyvs
  &redirect_uri=https%3A%2F%2Fmy-application.com
`

**Comment by breadpanz** [comment]
oh yes, I manage to get the code which is required in requesting here https://accounts.livechatinc.com/token

**Comment by venits** [comment]
Looks like problems with our server. If it is possible please create new application as `server-side-app`.

Maybe there is something wrong with application. If the problem prevail I will send this issue to our backend team.

**Comment by breadpanz** [comment]
Okay thank you

**Comment by breadpanz** [comment]
Okay sure, thanks :)

**Comment by breadpanz** [comment]
> Looks like problems with our server. If it is possible please create new application as `server-side-app`.
> 
> Maybe there is something wrong with application. If the problem prevail I will send this issue to our backend team.

I tried it in a new application but, still no luck.

**Comment by breadpanz** [comment]
Hi @venits it's okay now, the problem is on my side, I didn't notice the space before I put my `client_secret`.

**Comment by breadpanz** [comment]
Hi @venits it's okay now, the problem is on my side, I didn't notice the space before I put my `client_secret`

Thank you very much :)
